### ISSUE TITLE
Add H264 playback support

### ISSUE THREAD

**Issue by murillo128** [millicast/millicast-player-unreal-engine-plugin#13]
Currently we only support vp8/vp9 as video codec as h264 is not supported by the UE libwertc implementation due to licensing issues.

We would need to add support for h264 hardware decoding when available.

**Comment by MaxDorn96** [comment]
Hello. I've read that libwertc had some updates in 5 and 5.1.

Is it possible that the Plugin will soon be able to use other video codecs except vp8/vp9 or are the typical others such as 5264 still not supported in UE?

**Comment by Aeddon** [comment]
Need to vote for this feature.

It's nearly a must have nowadays...

**Comment by dbaldassi** [comment]
We now support H264 decoding by using our WebRTC library.
You can download it here : https://github.com/millicast/millicast-player-unreal-engine-plugin/releases/tag/1.7.0-millicast-webrtc
You need to be on the ``millicast-webrtc`` branch to use it. There are instructions how to integrate it into the plugins in the readme
