### ISSUE TITLE
Audio Consumer Crashing UE on Play in Editor

### ISSUE THREAD

**Issue by TroubledPrawn** [millicast/millicast-player-unreal-engine-plugin#19]
![image](https://user-images.githubusercontent.com/33198146/185159088-f1040a28-6a61-4af9-b611-883ef1f02933.png)

- Windows 
- UE launcher  

Issue: UE will crash immediately when connected to a live broadcast and the Audio Consumer is in the BP. 

I think this will be a simple fix, but how is the "Audio Consumer" supposed to be configured in the project?

Steps I have taken:

1. Add  "Millicast Audio Actor" to projects level
2. Inside my MillicastBP I have created a variable of type "Millicast Audio Actor" and named it Audio Consumer
3. Using the Event "On Audio Track" from the Millicast Subscriber Component I have connected the nodes as the tutorial explains. 
![image](https://user-images.githubusercontent.com/33198146/185161694-bd76e25f-20d8-4122-b942-9a870b6577c1.png)

I suspect the issue is due to the default value of the Audio Consumer Variable as seen in this picture
![image](https://user-images.githubusercontent.com/33198146/185162603-c63d5355-4a1c-432e-9bb7-2f68e3e2e9b3.png)

However I'm not sure how you connect this to the Audio Actor within the Level (if that even is the right approach).

**Comment by TroubledPrawn** [comment]
UPDATE:

To fix this the Audio Consumer variable needs to be set, I did this by using a set variable to the Level Blueprint, which referenced both the MillicastBP and the Millicast Audio Actor that are placed in the level. This way the connection is made between the variable and the Audio Actor placed in the level

**Comment by QuentinGarou** [comment]
It would be nice if it doesn't crash when nothing set since that is compiled fine in Blueprints 😄 
Also a bunch of other crashes happen when you are not authenticated but there no "easy" way to know this at first so a simple error message in the logs would be much appreciated rather than a crash (because of PeerConnection being nullptr)

I know this plugin is new and I really appreciate all the work you are doing so please don't take those comments badly 😄

**Comment by dbaldassi** [comment]
Thanks for reporting this. 
I will add a check if it is null, and log a warning message

**Comment by dbaldassi** [comment]
Should be fixed in [2b7c7c2](https://github.com/millicast/millicast-player-unreal-engine-plugin/commit/2b7c7c2cf5ff116906aa0398d366236e611cd144)
