### ISSUE TITLE
Crashes in SubscriberComponent & FScopeLock

### ISSUE THREAD

**Issue by improbable-andreaskrugersen** [millicast/millicast-player-unreal-engine-plugin#22]
In https://github.com/millicast/millicast-player-unreal-engine-plugin/commit/fb8ea52c2204e2cff09aed9b044da3db48726e2f you added `FScopeLock`s in various places. Can you elaborate on why these were added?

I suspect it was an attempt to fix crashes which we've also seen on our project, however I believe this is the wrong fix (and potentially bad for performance).

I'm not entirely sure what happens inside PeerConnection, but I suspect that some of the callbacks are not tied to the connection's lifetime. We got crashes suggesting that the component had already been deleted in the meantime. The SubscriberComponent captures a naked `this` pointer in several places. This is generally unsafe in Unreal if you can't guarantee that the lifetime of the lambda is tied to the lifetime of the class itself.

The default way to handle this is to use `AddWeakLambda` instead of `AddLambda` and capture `WeakThis = TWeakObjectPtr<UMillicastSubscriberComponent>(this)` instead of `this`.

So we now have

```
	OnConnectedHandle = WS->OnConnected().AddWeakLambda(this, [this]() { OnConnected(); });
	OnConnectionErrorHandle = WS->OnConnectionError().AddWeakLambda(this, [this](const FString& Error) { OnConnectionError(Error); });
	OnClosedHandle = WS->OnClosed().AddWeakLambda(this, [this](int32 StatusCode, const FString& Reason, bool bWasClean) { OnClosed(StatusCode, Reason, bWasClean); });
	OnMessageHandle = WS->OnMessage().AddWeakLambda(this, [this](const FString& Msg) { OnMessage(Msg); });
```
in `UMillicastSubscriberComponent::StartWebSocketConnection`. No crashes were observed in these lines of code since we made that fix.

and today we came upon a crash in the `LocalDescriptionObserver->SetOnSuccessCallback` which we are fixing with this pattern:

```
	CreateSessionDescriptionObserver->SetOnSuccessCallback([WeakThis = TWeakObjectPtr<UMillicastSubscriberComponent>(this)](const std::string& type, const std::string& sdp) {
	    if (WeakThis.IsValid()) {
	      UE_LOG(LogMillicastPlayer, Log, TEXT("pc.createOffer() | sucess\nsdp : %s"), *ToString(sdp));
              WeakThis->PeerConnection->SetLocalDescription(sdp, type);
	    }
	});
```

I was about to upstream those changes but then I saw that we're quite out of date and you fixed it differently

**Comment by dbaldassi** [comment]
Hi,
Thanks for sharing your fix. 
This seems better than using FScope,
I will modify it.
I have added these mutexes in case unsubscribe was called by the user during the negociation process, where two different thread can access the peerconnection and the websocket at the same time.

**Comment by improbable-andreaskrugersen** [comment]
Ah interesting. Maybe there's an argument for having both then. I don't know anything about the websocket internals so maybe the mutex is still required
