### ISSUE TITLE
Can't subscribe to a stream from C++ without a crash

### ISSUE THREAD

**Issue by QuentinGarou** [millicast/millicast-player-unreal-engine-plugin#23]
I wanted to use C++ to test your plugin and to avoid [this issue](https://github.com/millicast/millicast-player-unreal-engine-plugin/issues/21). However I keep having a crash about a FWeakObjectPtr that can't be copied in this method: UMillicastSubscriberComponent::Subscribe. The authentification goes well in the MillicastDirector but When I try to subscribe it crashes.

Here is the snippet of code I'm using to subscribe to the stream:
```
void UMillicastStreamSubsystem::SubscribeToStream(FString const& StreamName, TScriptInterface<IMillicastVideoConsumer> InVideoConsumer, TScriptInterface<IMillicastExternalAudioConsumer> InAudioConsumer)
{
    MediaSource = NewObject<UMillicastMediaSource>(this);
    MediaSource->AccountId = AccountId;
    MediaSource->StreamName = StreamName;
    MediaSource->bUseSubscribeToken = true;
    MediaSource->SubscribeToken = SubscribeToken;
    MediaSource->StreamUrl = StreamUrl;
    
    MillicastDirector = NewObject<UMillicastDirectorComponent>(this);
    MillicastDirector->Initialize(MediaSource);
    MillicastDirector->Authenticate();
    MillicastDirector->OnAuthenticated.AddDynamic(this, &ThisClass::OnAuthenticated);

    VideoConsumer = InVideoConsumer;
    AudioConsumer = InAudioConsumer;
}

void UMillicastStreamSubsystem::OnAuthenticated(FMillicastSignalingData const& SignalingData)
{
    static TScriptInterface<IMillicastExternalAudioConsumer> NewAudioConsumer = NewObject<UExternalAudioConsumerDummy>(this);
    MillicastSubscriber->Subscribe(SignalingData, AudioConsumer);
    MillicastSubscriber->OnVideoTrack.AddDynamic(this, &ThisClass::OnVideoTrack);
    UE_LOG(LogMillicastCustom, Warning, TEXT("Authenticated"));
}

void UMillicastStreamSubsystem::OnVideoTrack(UMillicastVideoTrack* VideoTrack)
{
    UE_LOG(LogMillicastCustom, Warning, TEXT("VideoTrack received"));
    VideoTrack->AddConsumer(VideoConsumer);
}
```
According to the documentation it is supposed to work fine even when nullptr is passed. I think that's actually most of the cases but even passing explicitly a nullptr crashes...

> 	/**
> 		Begin receiving video from Millicast. The optional ExternalAudioConsumer allows to perform custom audio handling.
> 		If nullptr is passed in, the default Unreal audio device is used.
> 	*/
> 	UFUNCTION(BlueprintCallable, Category = "MillicastPlayer", META = (DisplayName = "Subscribe"))
> 	bool Subscribe(const FMillicastSignalingData& InConnectionInformation, TScriptInterface<IMillicastExternalAudioConsumer> ExternalAudioConsumer);

Some advice on this would be highly appreciated;
Cheers,

**Comment by dbaldassi** [comment]
It is supposed to work with nullptr.
Do you have any logs, stack trace or anything to help debug ?

**Comment by QuentinGarou** [comment]
Unfortunately I don't have it anymore but you can create this class your self and see the crash I think
