### ISSUE TITLE
Error loading file "HAL/PlatformFilemanager.h" during build process.

### ISSUE THREAD

**Issue by ismarsantos** [millicast/millicast-player-unreal-engine-plugin#24]
I need a way to receive Video Streaming from Webcam inside Unreal Engine 5 in Linux environment

We followed the tutorial on the page below but during the process we noticed the following problem:

https://docs.dolby.io/streaming-apis/docs/player-plugin

We followed the tutorial on the page below but during the process an error occurs, it is not possible to load the file "HAL/PlatformFilemanager.h", we noticed that on the Linux platform, the correct class name is: "HAL/PlatformFileManager.h", with this change the engine was able to compile the plugin correctly.

https://github.com/millicast/millicast-player-unreal-engine-plugin/blob/main/Source/MillicastPlayer/Private/PCH.h

Now I need a way to transmit the webcam video of the user logged into the site to the engine, through webrtc, how can we do this, is it possible?

**Comment by dbaldassi** [comment]
I noticed also this header issue on linux, I have removed it in the dev branch of the plugin.

So your use case is : you are capturing with a webcam from a web browser and you would like to stream the video over webrtc and receive it in the player plugin ?

Then, you just have to publish your video over Millicast (you can use the Javascript SDK for this), and if you follow the Millicast Player documentation, you should be able to enter your Millicast credentials in the engine and receive the video in a texture.
