### ISSUE TITLE
Plugin doesn't work in 4.27.2 (PIE and standalone)

### ISSUE THREAD

**Issue by adrian-j-programmer** [millicast/millicast-player-unreal-engine-plugin#26]
We are trying to test the plugin in 4.27.2 and have followed the documentation to get a test case running. Unfortunately after having successfully subscribed to a stream and adding a video consumer to UMillicastVideoTrack, we are not receiving any frames at all.

**Comment by dbaldassi** [comment]
Which video codecare you using?

**Comment by adrian-j-programmer** [comment]
Actually, I think you pointed me in the right direction. Be default, the dashboard broadcasting uses h264 and this is what was causing the issue on my end. After changing to VP codecs it started to work correctly.
