### ISSUE TITLE
Millicast plugin causes UE to crash when being subscribed to a stream

### ISSUE THREAD

**Issue by adrian-j-programmer** [millicast/millicast-player-unreal-engine-plugin#27]
Hi, 

We have started to experience UE crashes after setting up the Millicast streams in our project. The callstack indicates this is caused by the following call :
`UMillicastVideoTrackImpl::OnFrame(webrtc::VideoFrame const&) [/project/Plugins/MillicastPlayer/Source/MillicastPlayer/Private/WebRTC/MillicastMediaTracks.cpp:38]`
We believe this is caused by the fact that the array that's being iterated through is being modified inside the iterative loop, which is not allowed. 
This is supported by the remaining callstack data:
`Error: appError called: Assertion failed: Addr < GetData() || Addr >= (GetData() + ArrayMax) [File:Runtime/Core/Public/Containers/Array.h] [Line: 1516]`
`(...) to use a container element (0x7f7d56ba86c0) which already comes from the container being modified (0x7f7d56ba86c0, ArrayMax: 4, ArrayNum: 1, SizeofElement: 16)!`

We hit this in the UE4 branch of the plugin.

**Comment by craig-johnston** [comment]
Quick attempt at resolution: https://github.com/millicast/millicast-player-unreal-engine-plugin/pull/28

**Comment by dbaldassi** [comment]
I have merged the PR in the UE4 branch,
you should be able to test it, let us know if it solves the crash.

**Comment by adrian-j-programmer** [comment]
We have been able to confirm the fix some time ago.
