### ISSUE TITLE
Millicast Player/Director not Instance Editable

### ISSUE THREAD

**Issue by MaxDorn96** [millicast/millicast-player-unreal-engine-plugin#31]
Hello.

I am currently running into the problem that I have a Millicast Screen Blueprint and I am trying to use multiple Instances of this Blueprint in my Level but with different Milicast Media Sources and Streams.

Once you place an Actor/Blueprint with Millicast Components (Subscriber and Director) in your World/Level you arent able to assign different Millicast Media Sources per Instance of that Blueprint.

I thought that would be still somewhat possible to solve since I could just make a Switch in the Blueprint itself and overwrite the Values of the Source for each individual Blueprint in my Level, but that isn't really that nice to handle and it seems that it doesn't work since my changes (Updating of the Source Values) is then used by any other Blueprint which uses this Default Source of the Blueprint.

So I would like to suggest that it is either able to overwrite the complete Milicast Media Source in Blueprints Subscriber and Director Components or it is able to change the Millicast Media Source Variable in the Details Panel of the Components in the World Outliner per Instance.

My current Solution was creating a duplicate of the Blueprint and changing the Default Milicast Media Source in the Components by hand, I really would like to do be able to change this kind of on runtime.

**Comment by dbaldassi** [comment]
>  it is able to change the Millicast Media Source Variable
It is possible to update the source values in the blueprint like this if that is what you are looking for.
![image](https://user-images.githubusercontent.com/49135375/200809397-001b262e-ffb5-4909-abda-2f482061dbac.png)

So you can create a media source in the blueprint and set the values like this.

But if I understand correctly your question, you would like to be able to directly have the value in the  Director UI panel ?

**Comment by MaxDorn96** [comment]
Yes. The problem I had with this is that if one Blueprint has one Millicast Media Source and I place this BlueprintActor 5 times in my level and everyone changes the Source with SetStreamName etc. it seems like everyone changes the one source everybody is sharing and in the end every Bleuprints Media Source has the same Values because the one who changed those last basically changed it for everybody (Tho I dont believe it should behave like this).

Still the easiest solution for me would be to be able to chane the Millicast media Source of the Millicast Director and Subscriber per Instance in any Level, or to Set the entire Millicast Source in Blueprint like GetMillicastSubscriber->Set Source.

Either one would be totally fine I believe.

![Screenshot 2022-11-09 115838](https://user-images.githubusercontent.com/52002313/200812718-4848ad94-00b3-4b3b-bff3-e87e78c62f87.png)


I hope it wouldn't be that much of a problem to implement this kind of accessability, since it would easy our worklflow a lot.

To be honest changing the source in Blueprints would be my most requested feature, since sometimes we use Millicast in Widgets which aren't instanced/placed in the Level directly

![Screenshot 2022-11-09 120034](https://user-images.githubusercontent.com/52002313/200813105-a4b7c7f1-6c58-4323-a32d-09ab1244d6b6.png)


With great regards,
Max

**Comment by dbaldassi** [comment]
If you just need a setter method in the subscriber/director to set the MillicastSource in the blueprint, it would not be a difficult thing to implement.

**Comment by MaxDorn96** [comment]
That would be great, that would work for me 100%, thank you very much, I'm looking forward to the next few Updates then.

Even tho it sounds easy, I wish you good luck that changing/adding this will go smoothly on your side.
