### ISSUE TITLE
need removeConsumer method in plugin

### ISSUE THREAD

**Issue by bkuermayr** [millicast/millicast-player-unreal-engine-plugin#33]
I have an application where I stream multiple camera streams into unreal engine, need the removeConsumer method to dynamically attach and remove incoming video streams to the consumer objects. Thanks!

**Comment by dbaldassi** [comment]
I have added the remove consumer method [785dfc0](https://github.com/millicast/millicast-player-unreal-engine-plugin/commit/785dfc010af6e070424e6cf0f9c83e4714326a1f)

**Comment by bkuermayr** [comment]
thanks! :)

**Comment by bkuermayr** [comment]
Still cannot 
![image](https://user-images.githubusercontent.com/45873859/203134075-6f7309bc-cb65-480d-b2ba-c11354efa22e.png)
