### ISSUE TITLE
Plugin no longer compiles on Linux

### ISSUE THREAD

**Issue by adrian-j-programmer** [millicast/millicast-player-unreal-engine-plugin#37]
When building the plugin in official UE5.1 linux container (and locally on a linux machine), the build fails because of the PLATFORM_XBOXONE define in the PCH. The quick workaround for us was to comment out this platform define, but it's probably not the right call. 

Here's the build error:
```
[3/83] Compile PCH.MillicastPlayer.h
In file included from /project/Plugins/MillicastPlayer/Intermediate/Build/Linux/B4D820EA/UnrealEditor/Development/MillicastPlayer/PCH.MillicastPlayer.h:383:
/project/Plugins/MillicastPlayer/Source/MillicastPlayer/Private/PCH.h:52:25: error: 'PLATFORM_XBOXONE' is not defined, evaluates to 0 [-Werror,-Wundef]
#if PLATFORM_WINDOWS || PLATFORM_XBOXONE
```

**Comment by dbaldassi** [comment]
I actually removed completly the PCH file. It should now compile on Linux.
I didn't test yet to compile on Linux but will do.
