### ISSUE TITLE
MillicastDirector SetMediaSource is missing

### ISSUE THREAD

**Issue by MaxDorn96** [millicast/millicast-player-unreal-engine-plugin#39]
Hello, based on my request a little while ago you've impleted the "SetMediaSource" function in the MillicastSubscriberComponent (Again thank you a lot for that), but it is missing in the MillicastDirectorComponent.

I am not sure if that is important at all, but as far as I know the correct steps to Recieve and Stream to Millicast is to Authenticate on the MillicastDirector and on Success you would Subscribe to that with the MillicastSubscriber.

I am now able to create 1 Blueprint which can get a Millicast Source based on an ID for example and Set it in the Subscriber but the Director will still need to have the MillicastSurce set manualy as a Default Value in the Component itself, which makes it not completly Instanciable without changing default values per Blueprint.

So my request would be to also add a "Set Millicast Media Source" Function to the Millicast Director, just like in the Millicast Subscriber, because then I believe I would have everything I need for my dynamic Millicast Blueprint.

Thanks again a lot for your help so far

**Comment by dbaldassi** [comment]
Yes that's right, I forgot to add it to the Director.
I will fix this

**Comment by dbaldassi** [comment]
I have added SetMediaSource to the director [68a00e9](https://github.com/millicast/millicast-player-unreal-engine-plugin/commit/68a00e9786b9cf76aa66bcedd8cb474e179c9935)
