### ISSUE TITLE
Real time mute not working

### ISSUE THREAD

**Issue by Koous61** [millicast/millicast-player-unreal-engine-plugin#40]
I need to disable the sound in real time, for this I use the SetEnabled method on AudioTrack, however I still hear the sound
![image](https://user-images.githubusercontent.com/33979092/208865276-f4b15a23-2f6d-4c1e-a5ab-eae5359091da.png)

**Comment by dbaldassi** [comment]
Calling SetEnabled indeed does not mute the audio, which might be a webrtc issue.
Ohterwise, what worked for me to mute the audio is to set the volume of the audio actor to 0: 
`MillicastAudioComponent->AudioComponent->SetVolumeMultiplier(0.0f);`
