### ISSUE TITLE
Can't compile both Millicast player and publisher

### ISSUE THREAD

**Issue by MaximeM** [millicast/millicast-player-unreal-engine-plugin#41]
We have module declaration colliding when packagin both :

FAudioDeviceModule
FWebRTCPeerConnection

Any way to fix this ?

Thank you!

**Comment by dbaldassi** [comment]
I will add namespaces to both plugin, that should solve it

**Comment by MaximeM** [comment]
That would be awesome  thanks

**Comment by dbaldassi** [comment]
I have added namespace for both plugins. ``Millicast::Publisher::`` for the publisher and ``Millicast::Player::`` for the player.
It is in the dev branch for the player and in the UE5.1 branch for the publisher.

**Comment by MaximeM** [comment]
It works thanks !
