### ISSUE TITLE
Crash when opening MillicastTexture

### ISSUE THREAD

**Issue by MaxDorn96** [millicast/millicast-player-unreal-engine-plugin#42]
Hello, im currently having the Problem of my Millicast Streams not beeing able to be seen in the App.

I broadcasted a Screen of mine and was able to see in Code that at that point the Authentication suceeded and he used the Valid MillicastTexture2DPlayer and OnVideoTrack added that to the consumer and it still didn't show me anything, but it did work beforehand.

I tried opening the MillicastTexture itself which is linked in the MillicastTexture2DPlayer and then Unreal crashed while trying to open said MillicastTexture itself

LowLevelFatalError [File:C:\UE5_1_Source\Engine\Source\Runtime\Engine\Classes\Engine\Texture.h] [Line: 1435] 
Pure virtual not implemented (UTexture::GetTextureClass)

0x00007ffd3ad8739c UnrealEditor-Engine.dll!UTexture::GetTextureClass() [C:\UE5_1_Source\Engine\Source\Runtime\Engine\Classes\Engine\Texture.h:1435]
0x000002041594d017 UnrealEditor-TextureEditor.dll!FTextureEditorToolkit::InitTextureEditor() [C:\UE5_1_Source\Engine\Source\Editor\TextureEditor\Private\TextureEditorToolkit.cpp:242]
0x0000020415931bbc UnrealEditor-TextureEditor.dll!FTextureEditorModule::CreateTextureEditor() [C:\UE5_1_Source\Engine\Source\Editor\TextureEditor\Private\TextureEditorModule.cpp:41]
0x00007ffd2b6c9be2 UnrealEditor-AssetTools.dll!FAssetTypeActions_Texture::OpenAssetEditor() [C:\UE5_1_Source\Engine\Source\Developer\AssetTools\Private\AssetTypeActions\AssetTypeActions_Texture.cpp:137]
0x00007ffd38ee0db3 UnrealEditor-UnrealEd.dll!UAssetEditorSubsystem::OpenEditorForAsset() [C:\UE5_1_Source\Engine\Source\Editor\UnrealEd\Private\Subsystems\AssetEditorSubsystem.cpp:402]
0x00007ffd38ee15a1 UnrealEditor-UnrealEd.dll!UAssetEditorSubsystem::OpenEditorForAssets_Advanced() [C:\UE5_1_Source\Engine\Source\Editor\UnrealEd\Private\Subsystems\AssetEditorSubsystem.cpp:476]
0x00007ffd38ee13aa UnrealEditor-UnrealEd.dll!UAssetEditorSubsystem::OpenEditorForAssets() [C:\UE5_1_Source\Engine\Source\Editor\UnrealEd\Private\Subsystems\AssetEditorSubsystem.cpp:592]
0x00007ffd02366d6b UnrealEditor-ContentBrowserAssetDataSource.dll!ContentBrowserAssetData::EditOrPreviewAssetFileItems() [C:\UE5_1_Source\Engine\Plugins\Editor\ContentBrowser\ContentBrowserAssetDataSource\Source\ContentBrowserAssetDataSource\Private\ContentBrowserAssetDataCore.cpp:288]
0x00007ffd02366fd8 UnrealEditor-ContentBrowserAssetDataSource.dll!ContentBrowserAssetData::EditOrPreviewItems() [C:\UE5_1_Source\Engine\Plugins\Editor\ContentBrowser\ContentBrowserAssetDataSource\Source\ContentBrowserAssetDataSource\Private\ContentBrowserAssetDataCore.cpp:308]
0x00007ffd0234e0da UnrealEditor-ContentBrowserAssetDataSource.dll!UContentBrowserAssetDataSource::BulkEditItems() [C:\UE5_1_Source\Engine\Plugins\Editor\ContentBrowser\ContentBrowserAssetDataSource\Source\ContentBrowserAssetDataSource\Private\ContentBrowserAssetDataSource.cpp:1238]
0x00007ffd2aaa9b2c UnrealEditor-ContentBrowser.dll!SContentBrowser::OnItemsActivated() [C:\UE5_1_Source\Engine\Source\Editor\ContentBrowser\Private\SContentBrowser.cpp:3020]
0x00007ffd2aa43e5c UnrealEditor-ContentBrowser.dll!TBaseSPMethodDelegateInstance<0,SContentBrowser,1,void __cdecl(TArrayView<FContentBrowserItem const ,int>,enum EAssetTypeActivationMethod::Type),FDefaultDelegateUserPolicy>::Execute() [C:\UE5_1_Source\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:295]
0x00007ffd2aaac20e UnrealEditor-ContentBrowser.dll!SAssetView::OnListMouseButtonDoubleClick() [C:\UE5_1_Source\Engine\Source\Editor\ContentBrowser\Private\SAssetView.cpp:3668]
0x00007ffd2aa52aaa UnrealEditor-ContentBrowser.dll!TBaseSPMethodDelegateInstance<0,SAssetView,1,void __cdecl(TSharedPtr<FAssetViewItem,1>),FDefaultDelegateUserPolicy>::ExecuteIfSafe() [C:\UE5_1_Source\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:312]
0x00007ffd2a9a6bc2 UnrealEditor-ContentBrowser.dll!TDelegate<void __cdecl(TSharedPtr<FAssetViewItem,1>),FDefaultDelegateUserPolicy>::ExecuteIfBound<void,0>() [C:\UE5_1_Source\Engine\Source\Runtime\Core\Public\Delegates\DelegateSignatureImpl.inl:639]
0x00007ffd2aac28dd UnrealEditor-ContentBrowser.dll!SListView<TSharedPtr<FAssetViewItem,1> >::Private_OnItemDoubleClicked() [C:\UE5_1_Source\Engine\Source\Runtime\Slate\Public\Widgets\Views\SListView.h:1115]
0x00007ffd2aaacc8b UnrealEditor-ContentBrowser.dll!STableRow<TSharedPtr<FAssetViewItem,1> >::OnMouseButtonDoubleClick() [C:\UE5_1_Source\Engine\Source\Runtime\Slate\Public\Widgets\Views\STableRow.h:423]
0x00007ffd3a39efb1 UnrealEditor-Slate.dll!FEventRouter::Route<FReply,FEventRouter::FBubblePolicy,FPointerEvent,<lambda_be18c20258355610e1a03a230227eebb> >() [C:\UE5_1_Source\Engine\Source\Runtime\Slate\Private\Framework\Application\SlateApplication.cpp:412]
0x00007ffd3a4053ec UnrealEditor-Slate.dll!FSlateApplication::RoutePointerDoubleClickEvent() [C:\UE5_1_Source\Engine\Source\Runtime\Slate\Private\Framework\Application\SlateApplication.cpp:5526]
0x00007ffd3a3f45f2 UnrealEditor-Slate.dll!FSlateApplication::ProcessMouseButtonDoubleClickEvent() [C:\UE5_1_Source\Engine\Source\Runtime\Slate\Private\Framework\Application\SlateApplication.cpp:5511]
0x00007ffd3a3ea8b8 UnrealEditor-Slate.dll!FSlateApplication::OnMouseDoubleClick() [C:\UE5_1_Source\Engine\Source\Runtime\Slate\Private\Framework\Application\SlateApplication.cpp:5474]
0x00007ffdae5220c2 UnrealEditor-ApplicationCore.dll!FWindowsApplication::ProcessDeferredMessage() [C:\UE5_1_Source\Engine\Source\Runtime\ApplicationCore\Private\Windows\WindowsApplication.cpp:2223]
0x00007ffdae507231 UnrealEditor-ApplicationCore.dll!FWindowsApplication::DeferMessage() [C:\UE5_1_Source\Engine\Source\Runtime\ApplicationCore\Private\Windows\WindowsApplication.cpp:2726]
0x00007ffdae524e42 UnrealEditor-ApplicationCore.dll!FWindowsApplication::ProcessMessage() [C:\UE5_1_Source\Engine\Source\Runtime\ApplicationCore\Private\Windows\WindowsApplication.cpp:1895]
0x00007ffdae5007f3 UnrealEditor-ApplicationCore.dll!FWindowsApplication::AppWndProc() [C:\UE5_1_Source\Engine\Source\Runtime\ApplicationCore\Private\Windows\WindowsApplication.cpp:925]
0x00007ffdcb55e7e8 USER32.dll!UnknownFunction []
0x00007ffdcb55e229 USER32.dll!UnknownFunction []
0x00007ffdae526249 UnrealEditor-ApplicationCore.dll!FWindowsPlatformApplicationMisc::PumpMessages() [C:\UE5_1_Source\Engine\Source\Runtime\ApplicationCore\Private\Windows\WindowsPlatformApplicationMisc.cpp:142]
0x00007ff624807453 UnrealEditor.exe!FEngineLoop::Tick() [C:\UE5_1_Source\Engine\Source\Runtime\Launch\Private\LaunchEngineLoop.cpp:5291]
0x00007ff6248234dd UnrealEditor.exe!GuardedMain() [C:\UE5_1_Source\Engine\Source\Runtime\Launch\Private\Launch.cpp:202]
0x00007ff6248235ca UnrealEditor.exe!GuardedMainWrapper() [C:\UE5_1_Source\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:107]
0x00007ff624826350 UnrealEditor.exe!LaunchWindowsStartup() [C:\UE5_1_Source\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:244]
0x00007ff624837d44 UnrealEditor.exe!WinMain() [C:\UE5_1_Source\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:282]
0x00007ff62483b0e6 UnrealEditor.exe!__scrt_common_main_seh() [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
0x00007ffdcae07614 KERNEL32.DLL!UnknownFunction []
0x00007ffdccca26a1 ntdll.dll!UnknownFunction []

![image](https://user-images.githubusercontent.com/52002313/212036089-a54447a0-0d68-4dd8-882a-12288939d08e.png)

I now wonder if I can't see anything in Unreal because the MillicastTexture itself is maybe broken?

I can replicate this error each time when trying to open a Millicast Texture.

I am currently working on the 5.1 branch in the commit "Add SetMediaSource to DirectorComponent" (68a00e9786b9cf76aa66bcedd8cb474e179c9935 [68a00e9])

**Comment by dbaldassi** [comment]
Seems there is one virtual method I did not override in the texture class.
I will fix it

**Comment by MaxDorn96** [comment]
Thanks a lot again for your fast response!

**Comment by dbaldassi** [comment]
I have override the method. You can find it in the main branch
