### ISSUE TITLE
MillicastSubscriber Event OnStopped isn't getting called - UE4_27

### ISSUE THREAD

**Issue by MaxDorn96** [millicast/millicast-player-unreal-engine-plugin#48]
Hello once again.

I was tasked to Track the Time a stream has been watched. It is a rather easy logic and it works, since I always know when the Authentication suceeds and I start getting Video/Audio with the AuthSuccess, OnVideoTrack and OnAudioTrack Events, so getting the start time of the stream works perfectly, but as far as I see there is only one Event called OnStopped, which is already implemented.

I tried to get this Event to get fired in Blueprints by Broadcasting a Millicast Stream through the Dolby Website directly and then stopping it.

As expected, at the moment the stream starts the Authentication succeds and I start to see the stream, but when I press stop in the Broadcasting overlay the stream/video/audio stops but the Event OnStopped is not called.

I guess this is a bug that it isn't called, but I would love to use this Event to track my stream time.

**Comment by rweber89** [comment]
@MaxDorn96 is what you are looking for potentially covered by the OnInactive event?

**Comment by dbaldassi** [comment]
As Roger said, Inactive event should be called when you stop publishing.
When you stop publishing, the viewer will still be subscribed to the stream after a certain amount of time, and when the stream is no longer being available, OnStopped is supposed to be called (it is currently not being implemented in the server side, you will likely never see OnStopped being called. It is reserved for future use)
