### ISSUE TITLE
Any plan for MacOS

### ISSUE THREAD

**Issue by MaximeM** [millicast/millicast-player-unreal-engine-plugin#52]
Hello,

Was wondering if they were any plan to support macOS?

**Comment by rweber89** [comment]
If you compile it with the right libwebrtc version on your mac from source, then yes. As UE4 and UE5 have different versions of libwebrtc that they compile against. Which version of UE are you using?

**Comment by dbaldassi** [comment]
UE source build only provide the binary of libwebrtc for Linux and Windows.
libwebrtc sources are pre-built by them and the binary + includes are put into the Engine/Source/ThirdParty folder of UE source tree

**Comment by dbaldassi** [comment]
I moved it to the branch ``millicast-webrtc``, for general use of our libwebrtc for any platform.
