### ISSUE TITLE
Expose PlayerStats to subscribers

### ISSUE THREAD

**Issue by improbable-andreaskrugersen** [millicast/millicast-player-unreal-engine-plugin#62]
While still on the `UE4.27` branch, I implemented a divergence to expose WebRTC stats to the `UMillicastSubscriber` component which we used to track metrics about incoming bandwidth.

Now that we've upgraded to the `dev` branch, I was excited to see that stats support was already present. Unfortunately, it's opinionated in that it only renders stats to the screen. We need to be able to extract that information to send it off to a metrics server. I could keep a divergence again but I'd much rather use the plugin as-is and find a solution that works for us both.

I don't know what your future plans for this are, so I'll just write down what we'd need on our side:

- Currently, the engine stat hook drives WebRTC stats polling. I'd like to change that so that stats can be polled independently of the consumer. They also just need to be polled once per frame. So if both the engine stats display and our metrics are turned on, we'd still only poll once but process the stats object in two different places
- `PlayerStats.h` is currently private. This would need to be made public to expose the `FPlayerStatsCollector` type
- There must be a way to access the `PeerConnection`'s stats collector from game code. In my divergence I routed this through the `MillicastSubscriberComponent` as a protected `OnStatsReceived` function. We could do that differently of course.

Would that direction be in line with your own plans? If so, would you want to do that change or are you happy to accept a PR?

**Comment by rweber89** [comment]
Thank you @improbable-andreaskrugersen I am working on a Simulcast issue right now but I`ll get on making this more accessible. As you can see we are making architectural improvements, this would be one of them.

I can get back to you on this with further details next week.

**Comment by improbable-andreaskrugersen** [comment]
@rweber89 Sounds great, thanks! I think we can live without these stats for a short while. I'm very happy that we're currently divergence-free though, so great work on the architectural changes so far 😃

**Comment by rweber89** [comment]
Addressed in 1bc22c57dd40b44e6d281927d08f8208b7f2f115 on the **dev** branch
