### ISSUE TITLE
Attempt to reconnect if web socket is closed

### ISSUE THREAD

**Issue by improbable-andreaskrugersen** [millicast/millicast-player-unreal-engine-plugin#64]
In a large scale test today I noticed that the WebRTC socket got closed on my own client as I wasn't receiving any data anymore and in my log I saw the `Millicast WebSocket Closed` message generated in `UMillicastSubscriberComponent::OnClosed`.

There are two issues here:
- I don't know why my socket was closed. There's a `Reason` string passed to that function which isn't logged. It should be
- More importantly, nothing is done in response to the socket being closed. There's no event being generated and the plugin also doesn't try to reconnect. We need at least an event telling us that the socket was closed so that we can make a decision whether we want to re-subscribe to the stream. We've had customer reports in past events that their in-game screen was black (i.e. they weren't receiving any data from the plugin) and I'm confident now that this is the reason

**Comment by rweber89** [comment]
As mentioned previously, this should be fixed now with the addition of https://github.com/millicast/millicast-player-unreal-engine-plugin/commit/2b5d40049c8dece1f89a1f9c6c527a86aa388771 to the dev branch

**Comment by rweber89** [comment]
Improved upon in 4c75f6d7c2e7eb519f9ae63a621d1fbf39fd87b0 on the **dev** branch
