### ISSUE TITLE
Second Millicast Stream breaks Audio

### ISSUE THREAD

**Issue by MaxDorn96** [millicast/millicast-player-unreal-engine-plugin#67]
Hello dear Millicast Team.

Currently we created a Blueprint which holds an MillicastAudioActor as an ChildActor in order for every Blueprint Instance in the Level to have their own AudioSource directly in themselves.

Both Blueprints in the Level have different Streamnames, Textures etc. so they can work Independent.

We were streaming to the first Blueprint Millicast-Wall and it worked great, the Sound and Video was on point, but as we also streamed on the Second Wall we weren't able to hear any Audio anymore, so the first Stream which is still running loses the Audio and the second one doesn't get any Audio either.

All we currently do is loop till a Stream is found, Subcribe to it if one was found and Add the Consumers, so apperently when the Second stream added it's MillicastAudioActor as an Consumer both broke.
We were able to replicate this multiple times.

We are currently using UE5.1 and are currently working with this commit (59589e9e01cc3ebd33726514a7a48927ae54d811 [59589e9]), I don't know if that was fixed already

**Comment by rweber89** [comment]
Please check if this is still an issue given the commits linked in my comment here: https://github.com/millicast/millicast-player-unreal-engine-plugin/issues/66#issuecomment-1547029977

You can now change your setup with the given changes to only pass in the individual AudioComponents in your setup.

**Comment by MaxDorn96** [comment]
Hey, since the latest Update this also works now, at least when Im testing in Editor.

I will try to test this again in a Packaged Version of the game and if it works I will close this Issue

**Comment by MaxDorn96** [comment]
We tested it today and it fixed our problem, we can now easily create a MillicastUniversialBP, have each of them use a different StreamName and use them independently inside one Level without them interupting each other, thanks a lot

**Comment by rweber89** [comment]
@MaxDorn96 that is great to hear. You are most welcome. If you notice anything else that is strange, hard to use or any things of such nature. I am here to improve the usability of the plugin! Just let me know!❤️
