### ISSUE TITLE
Troubles compiling this for UE5.0.3 on Ubuntu 22.04

### ISSUE THREAD

**Issue by Aeddon** [millicast/millicast-player-unreal-engine-plugin#69]
Hi there, 

I've noticed that the 5.0.3 tag/branch has been removed here recently.
The link from your docs end up here: https://github.com/millicast/millicast-player-unreal-engine-plugin/tree/UE5.0.3 with a 404.
And I'm running into troubles now to compile the latest source for UE5.0.3.

I end up with the following errors:

`[4/7] Compile Module.MillicastPlayer.cpp
In file included from /home/aeddon/MillicastBuild/HostProject/Plugins/MillicastPlayer/Intermediate/Build/Linux/B4D820EA/UnrealEditor/Development/MillicastPlayer/Module.MillicastPlayer.cpp:14:
/home/aeddon/MillicastBuild/HostProject/Plugins/MillicastPlayer/Source/MillicastPlayer/Private/WebRTC/PeerConnection.cpp:395:28: error: no member named 'make_ref_counted' in namespace 'rtc'
                        auto Transformer = rtc::make_ref_counted<FFrameTransformer>(this);
                                           ~~~~~^
/home/aeddon/MillicastBuild/HostProject/Plugins/MillicastPlayer/Source/MillicastPlayer/Private/WebRTC/PeerConnection.cpp:395:45: error: 'FFrameTransformer' does not refer to a value
                        auto Transformer = rtc::make_ref_counted<FFrameTransformer>(this);
                                                                 ^
`

Is this not compatible with 5.0.3 anymore (what a pity if this is true)

Any hint how to fix this?

Cheers Claude

**Comment by dbaldassi** [comment]
This issue has been solved in the dev branch, we will merge it soon into main

**Comment by Aeddon** [comment]
thanks, I will check out the dev branch then

**Comment by Aeddon** [comment]
Can't compile your dev branch either (other errors popup), seems I need to wait for your merge to main.

**Comment by rweber89** [comment]
Hi @Aeddon - I have addressed the compile issue. Please try again.

**Comment by Aeddon** [comment]
@rweber89 latest dev branch commit compiles now successfully on Linux. Need to check if it's actually also working now. 
Thanks so far, I will drop a note if all is working fine...

By the way: They Blueprint setup is rather complicated, do you have a demo project somewhere to download?
If not: Would be good to have, maybe an example folder inside this github repo would make sense?

**Comment by Aeddon** [comment]
@rweber89 

Finally got rid of the VS dependency and was able to load your example.
(https://github.com/millicast/millicast-player-ue5-example/tree/dev)

Turned out to cause the same problem:
![grafik](https://github.com/millicast/millicast-player-unreal-engine-plugin/assets/100358557/917df493-7407-438f-8bcd-2e5943d1b9ac)

**Comment by rweber89** [comment]
@Aeddon what was the VS Code dependency? As I am not aware of anything in our project that would cause this.

Please pull again from **dev** on the plugin repo. I have addressed this.

If you are using the MillicastActor from the example, simply add your video consumer to the VideoConsumers array. If you are using your own implementation, please do call RegisterVideoConsumer on the SubscriberComponent, before calling Subscribe.

**Comment by Aeddon** [comment]
@rweber89 

Thank you for your fast reaction!
I need to say support here is AAA. Never experienced something like this before. Big Kudos!

The VS Code dependency came from the fact that the .uproject  file was in the 5.1 format and obviously contained some stuff that 5.0 didn't know what to do with, so it asked for VS (don't ask me why exactly). Anyway, after I streamlined everything in correct 5.0 (copy&paste from an existing 5.0 project), this VS dialog popup was gone...

Let me investigate your changes now a bit, I will come back here with the results.

**Comment by Aeddon** [comment]
video works now perfectly. 

Thank you once again.

**Comment by rweber89** [comment]
@Aeddon You are most welcome. Any issues any time. Just let us know.

I`ll close this now.

**Comment by dbaldassi** [comment]
"Could not add video consumer", means either you did not instaciate the object you are passing or it has been garbage collected by unreal by the time AddConsumer is called
