### ISSUE TITLE
Texture stays black

### ISSUE THREAD

**Issue by siegetech** [millicast/millicast-player-unreal-engine-plugin#7]
Hey all, followed the official tutorial using 4.27 and 4.27 source.

Using the broadcast button and the viewer to validate that all is working.
According to unreal both authenticate and work ( i even get an error when there is no broadcast)
The media texture stays black. Can somebody provide a working 4.27 example project?

> 
> LogMillicastPlayer: pc.setLocalDescription() | sucess
> LogMillicastPlayer: Millicast WebSocket new Message : {"type":"response","transId":41,"data":{"sdp":"v=0\r\no=- 1644498107873 1 IN IP4 127.0.0.1\r\ns=semantic-sdp\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\na=ice-lite\r\na=msid-semantic: WMS *\r\na=group:BUNDLE 0 1\r\nm=audio 9 UDP/TLS/RTP/SAVPF 111\r\na=rtpmap:111 opus/48000/2\r\na=fmtp:111 minptime=10;useinbandfec=1\r
> \na=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=setup:passive\r\na=mid:0\r\na=msid:3f3ba348-bb72-4753-b344-9bb7e8a8c764 audio26723\r\na=sendonly\r\na=ice-ufrag:4fc2d18b0ede485c\r\na=ice-pwd:96c49045cee54d1453abd4e49bcdddb4510cf0dcf38f5ce1\r\na=fingerprint:sha-256 AC:43:3F:D4:1D:0B:96:0D:C2:D3:8F
> :F3:9F:06:E4:89:DF:11:FA:B9:89:72:90:67:8C:49:BF:A1:4E:89:59:07\r\na=candidate:1 1 UDP 2130706431 167.99.164.215 54972 typ host\r\na=ssrc:2027439574 cname:3f3ba348-bb72-4753-b344-9bb7e8a8c764\r\na=ssrc:2027439574 msid:3f3ba348-bb72-4753-b344-9bb7e8a8c764 audio26723\r\na=rtcp-mux\r\na=rtcp-rsize\r\nm=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101\r\na=rtpmap:9
> 6 VP8/90000\r\na=rtpmap:97 rtx/90000\r\na=rtpmap:98 VP9/90000\r\na=rtpmap:99 rtx/90000\r\na=rtpmap:100 VP9/90000\r\na=rtpmap:101 rtx/90000\r\na=fmtp:97 apt=96\r\na=fmtp:99 apt=98\r\na=fmtp:98 profile-id=0\r\na=fmtp:101 apt=100\r\na=fmtp:100 profile-id=2\r\na=rtcp-fb:96 goog-remb \r\na=rtcp-fb:96 ccm fir\r\na=rtcp-fb:96 nack \r\na=rtcp-fb:96 nack pli\r\na=rtc
> p-fb:96 transport-cc \r\na=rtcp-fb:98 goog-remb \r\na=rtcp-fb:98 ccm fir\r\na=rtcp-fb:98 nack \r\na=rtcp-fb:98 nack pli\r\na=rtcp-fb:98 transport-cc \r\na=rtcp-fb:100 goog-remb \r\na=rtcp-fb:100 ccm fir\r\na=rtcp-fb:100 nack \r\na=rtcp-fb:100 nack pli\r\na=rtcp-fb:100 transport-cc \r\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na
> =extmap:13 urn:3gpp:video-orientation\r\na=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id\r\na=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id\r\na=setup:passive\r\na=mid:1\r\na=msid:3f3ba348-bb72-4
> 753-b344-9bb7e8a8c764 video26724\r\na=sendonly\r\na=ice-ufrag:4fc2d18b0ede485c\r\na=ice-pwd:96c49045cee54d1453abd4e49bcdddb4510cf0dcf38f5ce1\r\na=fingerprint:sha-256 AC:43:3F:D4:1D:0B:96:0D:C2:D3:8F:F3:9F:06:E4:89:DF:11:FA:B9:89:72:90:67:8C:49:BF:A1:4E:89:59:07\r\na=candidate:1 1 UDP 2130706431 167.99.164.215 54972 typ host\r\na=ssrc:1041918821 cname:3f3ba34
> 8-bb72-4753-b344-9bb7e8a8c764\r\na=ssrc:1041918821 msid:3f3ba348-bb72-4753-b344-9bb7e8a8c764 video26724\r\na=ssrc:1321807945 cname:3f3ba348-bb72-4753-b344-9bb7e8a8c764\r\na=ssrc:1321807945 msid:3f3ba348-bb72-4753-b344-9bb7e8a8c764 video26724\r\na=ssrc-group:FID 1041918821 1321807945\r\na=rtcp-mux\r\na=rtcp-rsize\r\n","subscriberId":"e3aec36c370c4c8fa478aefbc
> 2681966","streamId":"[redacted]","streamViewId":1644275895707}}
> LogMillicastPlayer: Start Playout
> LogMillicastPlayer: Set remote description suceeded
> LogMillicastPlayer: Millicast WebSocket new Message : {"type":"event","name":"active","data":{"streamId":"[redacted]","sourceId":null,"tracks":[{"trackId":"audio","media":"audio"},{"trackId":"video","media":"video"}]}}

**Comment by murillo128** [comment]
What video codec are you using? is audio working?

**Comment by siegetech** [comment]
Thanks @murillo128  for the hint. Indeed, the default is not set to VP8/VP9. I understood that these are the only ones supported as of now. We were able to successfully change it and see a working image. Audio is something we are still trying to solve.
