### ISSUE TITLE
UE5 Fatal Error, Crashes EXCEPTION ACCESS VIOLATION or Freezes of App on Level switch

### ISSUE THREAD

**Issue by MaxDorn96** [millicast/millicast-player-unreal-engine-plugin#70]
Hello, we have been experiencing a few Crashes recently in different forms on Level switching.

I was able to backtrack it to the Authentication Function of the Millicast Director, if we never called this it never happens anymore.
We also tried it once more in a sepreate Project and were able to replicate it.

So basically to replicate this error we do the following.

- Have an empty Map with a Millicast Blueprint (Could be just as shown in the Documentations)
- Don't Loop the Authentication Function from the Millicast Director in this case
- On Button Press call the Authentication and also Open a Level directly as well (We used our Playercontroller which gets all actor of class in order to have the reference of the Millicast Actor to call Authenticate there)
- This doesnt happen every time but like 8 out of 10 tries either a complete Freeze, a Crash or even a Fatal Error takes place.

We think that Looping the Authentication and switching Levels is the cause of it all.
Maybe because the Authenticate Function fires an HTTP/REST call to the Millicast API and if one switches the Level, aka destory this Actor by doing so, creates a crash because the Answer from HTTP didn't arrive yet?

By calling this Function as well as opning a Level through a Button click we were able to replicate this behaviour way more easily, because before that we would just Delay a few seconds on BeginPlay and Open a new Level and waited for this to happen to verify.

It also seemed that Packaging for Distrubution was kind of necessary as well since without it this Crash didn't occur as often, only if you were to spam this button a lot.

Since we are required to somehow Loop the Authenticate in order to check if a Stream is currently active to Subscribe to it we would really need a fix for this because it seems like this is giving a randomness factor for a crash into our Application.

We are currently working on this commit with UE5.1.1 Binary Engine (516084dc4c682f39d43e981a2abb4db1ce7bf47a)

**Comment by MaxDorn96** [comment]
I just tested it again with the least Millicast calls possible to ensre it isnt a weird bug

![image](https://github.com/millicast/millicast-player-unreal-engine-plugin/assets/52002313/c740b06b-c01d-4fcb-b529-2212d049cd92)

![image](https://github.com/millicast/millicast-player-unreal-engine-plugin/assets/52002313/853a3cfd-ddcb-416a-9f0f-b3aff07f6f3d)

![image](https://github.com/millicast/millicast-player-unreal-engine-plugin/assets/52002313/271c61ea-55f7-4510-a702-7d6c05334975)


This here was my Setup and it still crashed as mentioned before.

We basically have a Hardcoded MillicastSource which I set als default in the components.
The last Image is our Playercontroller. We basically just call StartAuth and OpenLevel on a Keyboard Press and then it will crash in Builds, sometimes it also crashes the Editor but not as frequently.

**Comment by MaxDorn96** [comment]
In our original Blueprint which is a little more advanced than this we basically start a Timer Event (Basically a Loop with Delay) to try to Authenticate since we need to check if a Stream is currently active every now and then.

So we basically try to Authenticate like every 5 seconds.
If we succed we stop the loop and properly Subscribe to the Stream and OnActive will get played as intended.

Since the Mediasource doesnt really change on runtime (So we always use the same Streamname for 1 Blueprint) we never need to enter this loop again since we are already subscribed, so if one ends the stream and someone else starts a stream the OnActive event just is getting called so a new Authentication is not needed.

We basically can only run into this error if I were to join a world where nobody streams at the moment. If I then happen to switch the Level right when the loop calls Authenticate I might crash my Application, thats basically the sum of Information I have, I hope this helps somewhat.

I dont really know exatcly why it crashes since Unreal doesnt give me any explicit Error message, sorry for not beeing a big help on that front

**Comment by MaxDorn96** [comment]
I wanna thank you once more for your fast response times and the way how you listen to the community.

We are working with some other Plugins as well which don't have this Level of support.

I hope I was able to give you enough Informations for you. Thanks again, you are amazing.

**Comment by rweber89** [comment]
Hi @MaxDorn96 please try with the latest changes on the **dev** branch.

**Comment by rweber89** [comment]
I am closing this now. @MaxDorn96 I wouldn`t be able to do it without your feedback.
