### ISSUE TITLE
Require Apple Silicon Support and support for iOS and Android ARM 64 platforms

### ISSUE THREAD

**Issue by dzeitman** [millicast/millicast-player-unreal-engine-plugin#72]
### Require Apple Silicon Support and support for iOS and Android ARM 64 platforms:

Investigating  Streaming Plugins for UE; Require Apple Silicon Support and support for iOS and Android ARM 64 platforms mid July-August time-frame.  

1. How realistic is that timeline with the Dolby.io roadmap? 
2. Will this product have ongoing support and updates across all versions of UE?
3. Will this plugin be 100% compatible with other Dolby.io APIs, such as Spatial Chat?

**Comment by dbaldassi** [comment]
The plugin now support iOS and Android
