### ISSUE TITLE
Spatialize the sound source for more immersive playback.

### ISSUE THREAD

**Issue by dbaldassi** [millicast/millicast-player-unreal-engine-plugin#8]
Electra is the new media player of the unreal engine that supports h264 streams and the media audio component within the unreal engine.
This allows to spatialize the sound source for more immersive playback.
We should take a look at elektra and see if we can attach an audio source to an actor to allow spatialization instead of playing 2D audio.

**Comment by RaedAbbas** [comment]
Hi,
How did you play audio in Unreal BP actor (even 2D is fine for now)?

**Comment by dbaldassi** [comment]
Hi,
In the dev branch you have a AMillicastAudio actor. You can drag it into you scene to play spatial audio.
Then, add the object in your blueprint, and you have a method in the Subscriber component which is "AddExternalAudioConsumer", which you must use to add you actor in order to receive the audio data.
You can do you own audio actor by inheriting the interface IExternalAudioConsumer.
For now all audio track can only be received by one actor.
I'm currently modifying the API to render several audio tracks at once.

**Comment by RaedAbbas** [comment]
ah.. the dev branch.. I didn't see that. I'll check it out. Thank you for sharing :)

**Comment by RaedAbbas** [comment]
cool.. this is working as expected for 1 streamer, many thanks. The question is: do we know the streamer id emitting the sound? What I would like to do is to find the StreamerID/name for each speaker and store them in a variable locally.

**Comment by dbaldassi** [comment]
Otherwise, you get the stream id in the ``OnActive`` event.

**Comment by RaedAbbas** [comment]
yeah. makes sense.. Well done mate and thank you for your help. Looking forward for your audio solution :)

**Comment by dbaldassi** [comment]
I just pushed to commit to render each video and audio track. 
It changes a bit the api and I did not documented it yet.
Basically, you have two event on the subscriber component : OnVideoTrack, OnAudioTrack, which give you a track object. And you can add a consumer to this track.
As an example, my blueprint : 
![image](https://user-images.githubusercontent.com/49135375/173836295-453b89a8-69ce-430b-886e-eeeaac403267.png)
I have an array of audioconsummers, which are AudioMillicastActor instance add add it as a consumer to each new track I am receiving.
Note that this is still in dev branch, so if you experience a crash, let me know.

**Comment by RaedAbbas** [comment]
Awesome.. I'll give it a test this evening.. Again, many thanks and well done 👍🏾

**Comment by RaedAbbas** [comment]
I tried this but unfortunately it crashed
![image](https://user-images.githubusercontent.com/87811633/174005231-3ebe1fb8-c69b-4c8f-8e99-a0ee40558c33.png)

**Comment by RaedAbbas** [comment]
upon restart it also breaks
![image](https://user-images.githubusercontent.com/87811633/174005500-e9f6d601-2189-4d24-96da-b08ffbc37eeb.png)

**Comment by RaedAbbas** [comment]
I tried to add more than 1 audio actor and streamed from 2 different streamer names on the same machine and got this error
![image](https://user-images.githubusercontent.com/87811633/174280438-bfe58d5b-a720-4447-9af4-2afd28a43cd1.png)

**Comment by RaedAbbas** [comment]
> I just pushed to commit to render each video and audio track. It changes a bit the api and I did not documented it yet. Basically, you have two event on the subscriber component : OnVideoTrack, OnAudioTrack, which give you a track object. And you can add a consumer to this track. As an example, my blueprint : ![image](https://user-images.githubusercontent.com/49135375/173836295-453b89a8-69ce-430b-886e-eeeaac403267.png) I have an array of audioconsummers, which are AudioMillicastActor instance add add it as a consumer to each new track I am receiving. Note that this is still in dev branch, so if you experience a crash, let me know.

btw, how do you set elemetns in AudioConsumers? Do you just spawn AudioActors and add them to the array?

**Comment by dbaldassi** [comment]
Basically, yes.
I have a public array of consumers in the blueprint, so I can add the audio actor from the scene.

**Comment by dbaldassi** [comment]
Looking at your bp 
![image](https://user-images.githubusercontent.com/49135375/174549454-1a9e05e7-eaab-47d7-a731-157c9b39a708.png)
You should avoid to put an audio consumer on both the subscribe method and on the OnTrack event. You should go for one or the other.

**Comment by Anjee1DEV** [comment]
Hi dbaldssi, I hope you are okay, Idk if you could help me on my project, I have tried this and the tutorial on the Dolby documentation but I cant get my stream to play audio. 
if you could explain me how to get audio in detail or what I am doing wrong I would thank you a lot.
