### ISSUE TITLE
Can't close/reopen my PR

### ISSUE THREAD

**Issue by improbable-andreaskrugersen** [millicast/millicast-player-unreal-engine-plugin#9]
I can neither close https://github.com/millicast/millicast-player-unreal-engine-plugin/pull/1 nor comment on it anymore since it's locked to collaborators. At the same time I can't create a new PR for my branch since this PR is still open. Can you please close it?

**Comment by murillo128** [comment]
done, are you able to create a new PR now?

**Comment by improbable-andreaskrugersen** [comment]
Thanks, opened https://github.com/millicast/millicast-player-unreal-engine-plugin/pull/10
